version: "3.8"

services:
  app:
    build:
      context: .
    restart: always
    container_name: nirsii_api_router
    command: uvicorn main:app --host 0.0.0.0 --port 4396 --workers 2
    ports:
      - "4396:4396"
    networks:
      - seq_backend

networks:
  seq_backend: