version: "3.8"

services:
  app:
    build:
      context: .
    restart: always
    container_name: nirsii_api_router
    command: uvicorn main:app --host 0.0.0.0 --port 4396 --workers 2
    ports:
      - "4396:4396"
    networks:
      - rna_network
      - apt_network
      - apt_mol_network
      - prot_prot_network
      - ccp_gen_network
      - aptamer_gen_network

networks:
  rna_network:
    external: true
    name: rna_rna_seq_backend

  apt_network:
    external: true
    name: aptamer_protein_seq_backend

  apt_mol_network:
    external: true
    name: aptamer_small_molecule_seq_backend

  prot_prot_network:
    external: true
    name: protein_protein_seq_backend

  ccp_gen_network:
    external: true
    name: cppgeneration_seq_backend

  aptamer_gen_network:
    external: true
    name: aptamer_gen_model_seq_backend
