import torch


def causal_mask(size):
        # Creating a square matrix of dimensions 'size x size' filled with ones
        mask = torch.triu(torch.ones(1, size, size), diagonal = 1).type(torch.int)
        return mask == 0


def greedy_decode(model, source, source_mask, tokenizer_tgt, max_len, device):
    """
    Модифицированная функция декодирования с проверками

    Args:
        model: объект Transformer
        source: тензор эмбеддингов исходной последовательности [1, seq_len, d_model]
        source_mask: маска исходной последовательности [1, 1, 1, seq_len]
        tokenizer_tgt: токенизатор целевого языка
        max_len: максимальная длина генерируемой последовательности
        device: устройство (cpu/cuda)

    Returns:
        Сгенерированную последовательность токенов
    """
    # Проверки входных данных
    assert source.dim() == 3, f"Ожидается 3D тензор (batch=1), получено {source.dim()}D"
    assert source.size(0) == 1, f"Ожидается batch size=1, получено {source.size(0)}"
    assert source_mask.size(0) == 1, f"Ожидается batch size=1 для маски, получено {source_mask.size(0)}"

    # Получаем специальные токены
    sos_idx = tokenizer_tgt.token_to_id('[SOS]')
    eos_idx = tokenizer_tgt.token_to_id('[EOS]')


    # Проверка наличия специальных токенов
    assert sos_idx is not None, "Токен [SOS] не найден в словаре"
    assert eos_idx is not None, "Токен [EOS] не найден в словаре"

    # Кодируем исходную последовательность
    encoder_output = model.encode(source, source_mask)

    # Инициализируем декодер с [SOS] токена
    decoder_input = torch.empty(1, 1).fill_(sos_idx).type_as(source).to(device)

    # Основной цикл генерации
    for _ in range(max_len):
        # Проверка размера входного тензора декодера
        if decoder_input.size(1) >= max_len:
            break

        # Создаем маску для декодера
        decoder_mask = causal_mask(decoder_input.size(1)).type_as(source_mask).to(device)

        # Декодируем
        out = model.decode(
            encoder_output,
            source_mask,
            decoder_input,
            decoder_mask
        )

        # Проекция на словарь
        prob = model.project(out[:, -1])

        # Проверка выходов проекции
        assert not torch.isnan(prob).any(), "Обнаружены NaN в выходе проекции"
        assert prob.isfinite().all(), "Обнаружены бесконечные значения в выходе проекции"

        # Жадное декодирование
        _, next_word = torch.max(prob, dim=1)

        # Проверка нового токена
        if next_word.item() not in tokenizer_tgt.id_to_token_map:
            print(f"⚠️ Обнаружен неизвестный ID токена: {next_word.item()}")
            break

        # Добавляем новый токен
        decoder_input = torch.cat([
            decoder_input,
            torch.empty(1, 1).type_as(source).fill_(next_word.item()).to(device)
        ], dim=1)

        # Проверка на EOS
        if next_word == eos_idx:
            break
        text_so_far = tokenizer_tgt.decode(decoder_input.squeeze(0).tolist())
        if len(text_so_far) >= max_len:
            break

    # Проверка выходной последовательности
    generated_seq = decoder_input.squeeze(0)
    assert generated_seq.dim() == 1, f"Ожидается 1D тензор, получено {generated_seq.dim()}D"

    return decoder_input.squeeze(0) # Sequence of tokens generated by the decoder



def beam_search_decode(model, source, source_mask, tokenizer_tgt, max_len, device, beam_width=7, alpha=0.05):
    """
    Beam search decoding for the Transformer model

    Args:
        model: Your Transformer model
        source: Input embedding tensor [1, d_model]
        source_mask: Mask for source [1, 1, 1]
        tokenizer_tgt: Target tokenizer
        max_len: Maximum sequence length
        device: 'cuda' or 'cpu'
        beam_width: Number of beams to keep at each step

    Returns:
        The best sequence found by beam search
    """
    sos_idx = tokenizer_tgt.token_to_id('[SOS]')
    pad_idx = tokenizer_tgt.token_to_id('[PAD]')
    eos_idx = tokenizer_tgt.token_to_id('[EOS]')

    assert source.dim() == 3 and source.size(0) == 1
    assert source_mask.size(0) == 1
    assert all(idx is not None for idx in (sos_idx, pad_idx, eos_idx))

    # (sequence, raw_score, length_in_tokens)
    beams = [([sos_idx], 0.0, 1)]

    with torch.no_grad():
        encoder_output = model.encode(source, source_mask)

    for _ in range(max_len):
        new_beams = []

        for seq, raw_score, length in beams:
            decoded_text = tokenizer_tgt.decode(seq)

            # If already completed or char limit reached — keep as-is with normalization
            if seq[-1] == eos_idx or len(decoded_text) >= max_len:
                final_score = raw_score / (length ** alpha)
                new_beams.append((seq, final_score, length))
                continue

            # Prepare decoder input
            decoder_input = torch.tensor(seq).unsqueeze(0).to(device)
            decoder_mask = causal_mask(decoder_input.size(1)).type_as(source_mask).to(device)

            # Decode next token probabilities
            out = model.decode(encoder_output, source_mask, decoder_input, decoder_mask)
            probs = torch.log_softmax(model.project(out[:, -1]), dim=-1)

            # Top-k candidates
            topk_probs, topk_ids = probs.topk(beam_width)

            for i in range(beam_width):
                new_token = topk_ids[0, i].item()
                new_seq = seq + [new_token]
                new_raw_score = raw_score + topk_probs[0, i].item()
                new_length = length + 1

                # Apply length penalty if close to limit
                if new_length > max_len * 0.9:
                    new_raw_score -= (new_length / max_len) * 2

                # Check char length for this new candidate
                decoded_new = tokenizer_tgt.decode(new_seq)
                if len(decoded_new) >= max_len or new_token == eos_idx:
                    final_score = new_raw_score / (new_length ** alpha)
                    new_beams.append((new_seq, final_score, new_length))
                else:
                    new_beams.append((new_seq, new_raw_score, new_length))

        # After expanding all beams, prune
        beams = sorted(new_beams, key=lambda x: x[1], reverse=True)[:beam_width]

        # Early stopping if all beams ended
        if all(seq[-1] == eos_idx or len(tokenizer_tgt.decode(seq)) >= max_len for seq, _, _ in beams):
            break

    # Pick best completed sequence
    completed = [(seq, score) for seq, score, _ in beams if seq[-1] == eos_idx or len(tokenizer_tgt.decode(seq)) >= max_len]
    if completed:
        best_seq = max(completed, key=lambda x: x[1])[0]
    else:
        best_seq = max(beams, key=lambda x: x[1] / (x[2] ** alpha))[0]

    return torch.tensor(best_seq[1:], device=device)  # remove SOS


def beam_search_decode_2(
    model, source, source_mask, tokenizer_tgt, max_len, device,
    beam_width=7, alpha=0.6, repetition_penalty=1.1, repetition_window=10
):
    sos_idx = tokenizer_tgt.token_to_id('[SOS]')
    eos_idx = tokenizer_tgt.token_to_id('[EOS]')
    assert sos_idx is not None and eos_idx is not None

    beams = [([sos_idx], 0.0)]  # (sequence, log-prob sum)
    completed = []

    with torch.no_grad():
        encoder_output = model.encode(source, source_mask)

    for _ in range(max_len):
        new_beams = []

        for seq, score in beams:
            if seq[-1] == eos_idx:
                completed.append((seq, score))
                continue

            decoder_input = torch.tensor(seq, device=device).unsqueeze(0)
            decoder_mask = causal_mask(decoder_input.size(1)).type_as(source_mask).to(device)
            logits = model.project(model.decode(encoder_output, source_mask, decoder_input, decoder_mask)[:, -1])

            # Apply sliding-window repetition penalty
            if repetition_penalty != 1.0 and len(seq) > 1:
                window = seq[-repetition_window:]
                for tok in set(window):
                    if logits[0, tok] < 0:
                        logits[0, tok] *= repetition_penalty
                    else:
                        logits[0, tok] /= repetition_penalty

            log_probs = torch.log_softmax(logits, dim=-1)
            topk_log_probs, topk_ids = log_probs.topk(beam_width)

            for i in range(beam_width):
                new_seq = seq + [topk_ids[0, i].item()]
                new_score = score + topk_log_probs[0, i].item()
                new_beams.append((new_seq, new_score))

        # Keep top beams with length normalization
        beams = sorted(
            new_beams, 
            key=lambda x: x[1] / ((5 + len(x[0]))**alpha / (5 + 1)**alpha),
            reverse=True
        )[:beam_width]

    # Add unfinished beams to completed list
    completed += beams

    # Return best-scoring sequence
    best_seq = max(
        completed,
        key=lambda x: x[1] / ((5 + len(x[0]))**alpha / (5 + 1)**alpha)
    )[0]

    return torch.tensor(best_seq[1:], device=device)  # remove SOS



def top_k_decode(model, source, source_mask, tokenizer_tgt, max_len, device, k=5):
    """
    Модифицированная функция декодирования с проверками

    Args:
        model: объект Transformer
        source: тензор эмбеддингов исходной последовательности [1, seq_len, d_model]
        source_mask: маска исходной последовательности [1, 1, 1, seq_len]
        tokenizer_tgt: токенизатор целевого языка
        max_len: максимальная длина генерируемой последовательности
        device: устройство (cpu/cuda)

    Returns:
        Сгенерированную последовательность токенов
    """
    # Проверки входных данных
    assert source.dim() == 3, f"Ожидается 3D тензор (batch=1), получено {source.dim()}D"
    assert source.size(0) == 1, f"Ожидается batch size=1, получено {source.size(0)}"
    assert source_mask.size(0) == 1, f"Ожидается batch size=1 для маски, получено {source_mask.size(0)}"

    # Получаем специальные токены
    sos_idx = tokenizer_tgt.token_to_id('[SOS]')
    eos_idx = tokenizer_tgt.token_to_id('[EOS]')


    # Проверка наличия специальных токенов
    assert sos_idx is not None, "Токен [SOS] не найден в словаре"
    assert eos_idx is not None, "Токен [EOS] не найден в словаре"

    # Кодируем исходную последовательность
    encoder_output = model.encode(source, source_mask)

    # Инициализируем декодер с [SOS] токена
    decoder_input = torch.empty(1, 1).fill_(sos_idx).type_as(source).to(device)

    # Основной цикл генерации
    for _ in range(max_len):
        # Проверка размера входного тензора декодера
        # if decoder_input.size(1) >= max_len:
        #     break

        decoded_text = tokenizer_tgt.decode(decoder_input.squeeze(0).tolist())
        if len(decoded_text) >= max_len:
            break

        # Создаем маску для декодера
        decoder_mask = causal_mask(decoder_input.size(1)).type_as(source_mask).to(device)

        # Декодируем
        out = model.decode(
            encoder_output,
            source_mask,
            decoder_input,
            decoder_mask
        )

        # Проекция на словарь
        logits = model.project(out[:, -1])
        probs = torch.softmax(logits, dim=-1)

        # Проверка выходов проекции
        assert not torch.isnan(probs).any(), "Обнаружены NaN в выходе проекции"
        assert probs.isfinite().all(), "Обнаружены бесконечные значения в выходе проекции"

        
        # Apply top-k sampling
        top_k_probs, top_k_indices = torch.topk(probs, k, dim=-1)
        
        # Renormalize probabilities
        top_k_probs = top_k_probs / top_k_probs.sum(dim=-1, keepdim=True)
        
        # Sample from top-k
        sampled_index = torch.multinomial(top_k_probs, num_samples=1)
        next_word = top_k_indices.gather(-1, sampled_index).squeeze(-1).item()


        # Проверка нового токена
        if next_word not in tokenizer_tgt.id_to_token_map:
            print(f"⚠️ Обнаружен неизвестный ID токена: {next_word.item()}")
            break

        # Добавляем новый токен
        decoder_input = torch.cat([
            decoder_input,
            torch.empty(1, 1).type_as(source).fill_(next_word).to(device)
        ], dim=1)

        # Проверка на EOS
        if next_word == eos_idx:
            break

    # Проверка выходной последовательности
    generated_seq = decoder_input.squeeze(0)
    assert generated_seq.dim() == 1, f"Ожидается 1D тензор, получено {generated_seq.dim()}D"

    return decoder_input.squeeze(0) # Sequence of tokens generated by the decoder





def top_p_decode(model, source, source_mask, tokenizer_tgt, max_len, device, top_p=0.9):
    """
    Модифицированная функция декодирования с проверками

    Args:
        model: объект Transformer
        source: тензор эмбеддингов исходной последовательности [1, seq_len, d_model]
        source_mask: маска исходной последовательности [1, 1, 1, seq_len]
        tokenizer_tgt: токенизатор целевого языка
        max_len: максимальная длина генерируемой последовательности
        device: устройство (cpu/cuda)

    Returns:
        Сгенерированную последовательность токенов
    """
    # Проверки входных данных
    assert source.dim() == 3, f"Ожидается 3D тензор (batch=1), получено {source.dim()}D"
    assert source.size(0) == 1, f"Ожидается batch size=1, получено {source.size(0)}"
    assert source_mask.size(0) == 1, f"Ожидается batch size=1 для маски, получено {source_mask.size(0)}"

    # Получаем специальные токены
    sos_idx = tokenizer_tgt.token_to_id('[SOS]')
    eos_idx = tokenizer_tgt.token_to_id('[EOS]')


    # Проверка наличия специальных токенов
    assert sos_idx is not None, "Токен [SOS] не найден в словаре"
    assert eos_idx is not None, "Токен [EOS] не найден в словаре"

    # Кодируем исходную последовательность
    encoder_output = model.encode(source, source_mask)

    # Инициализируем декодер с [SOS] токена
    decoder_input = torch.empty(1, 1).fill_(sos_idx).type_as(source).to(device)

    # Основной цикл генерации
    for _ in range(max_len):
        # # Проверка размера входного тензора декодера
        # if decoder_input.size(1) >= max_len:
        #     break

        decoded_text = tokenizer_tgt.decode(decoder_input.squeeze(0).tolist())
        if len(decoded_text) >= max_len:
            break

        # Создаем маску для декодера
        decoder_mask = causal_mask(decoder_input.size(1)).type_as(source_mask).to(device)

        # Декодируем
        out = model.decode(
            encoder_output,
            source_mask,
            decoder_input,
            decoder_mask
        )

                # Проекция на словарь
        logits = model.project(out[:, -1])
        probs = torch.softmax(logits, dim=-1)

        # Проверка выходов проекции
        assert not torch.isnan(probs).any(), "Обнаружены NaN в выходе проекции"
        assert probs.isfinite().all(), "Обнаружены бесконечные значения в выходе проекции"

        # Применяем top-p (nucleus) семплирование
        sorted_probs, sorted_indices = torch.sort(probs, descending=True)
        cumulative_probs = torch.cumsum(sorted_probs, dim=-1)

        # Удаляем токены с кумулятивной вероятностью > top_p
        sorted_indices_to_remove = cumulative_probs > top_p
        # Сдвигаем, чтобы оставить хотя бы один токен
        sorted_indices_to_remove[..., 1:] = sorted_indices_to_remove[..., :-1].clone()
        sorted_indices_to_remove[..., 0] = False

        # Обнуляем маловероятные токены
        indices_to_remove = sorted_indices[sorted_indices_to_remove].unsqueeze(0)
        # Создаем маску для оригинальных индексов
        scatter_mask = torch.zeros_like(probs, dtype=torch.bool)
        scatter_mask.scatter_(1, indices_to_remove, True)
        
        # Обнуляем маловероятные токены
        probs[scatter_mask] = 0.0
        
        # Нормализуем оставшиеся вероятности
        if probs.sum() > 0:
            probs.div_(probs.sum())
        else:
            # Если все токены исключены, берем самый вероятный
            probs = torch.zeros_like(probs)
            probs[0, sorted_indices[0, 0]] = 1.0

        # Семплируем следующий токен
        next_word = torch.multinomial(probs, num_samples=1).item()

        # Проверка нового токена
        if next_word not in tokenizer_tgt.id_to_token_map:
            print(f"⚠️ Обнаружен неизвестный ID токена: {next_word}")
            break

        # Добавляем новый токен
        decoder_input = torch.cat([
            decoder_input,
            torch.empty(1, 1).type_as(source).fill_(next_word).to(device)
        ], dim=1)

        # Проверка на EOS
        if next_word == eos_idx:
            break

    # Проверка выходной последовательности
    generated_seq = decoder_input.squeeze(0)
    assert generated_seq.dim() == 1, f"Ожидается 1D тензор, получено {generated_seq.dim()}D"

    return decoder_input.squeeze(0) # Sequence of tokens generated by the decoder

def top_p_decode_2(
    model, source, source_mask, tokenizer_tgt, max_len, device,
    top_p=0.9, temperature=1.0, repetition_penalty=1.2, min_tokens_to_keep=5
):
    sos_idx = tokenizer_tgt.token_to_id('[SOS]')
    eos_idx = tokenizer_tgt.token_to_id('[EOS]')

    assert sos_idx is not None and eos_idx is not None

    encoder_output = model.encode(source, source_mask)
    decoder_input = torch.full((1, 1), sos_idx, dtype=torch.long, device=device)

    generated_tokens = set()  # for repetition penalty

    for _ in range(max_len):
        decoder_mask = causal_mask(decoder_input.size(1)).type_as(source_mask).to(device)
        out = model.decode(encoder_output, source_mask, decoder_input, decoder_mask)
        logits = model.project(out[:, -1])

        # Temperature scaling
        logits = logits / temperature
        probs = torch.softmax(logits, dim=-1)

        # Apply repetition penalty
        for tok in generated_tokens:
            probs[0, tok] /= repetition_penalty

        # Sort and apply nucleus (top-p) filtering
        sorted_probs, sorted_indices = torch.sort(probs, descending=True)
        cumulative_probs = torch.cumsum(sorted_probs, dim=-1)

        cutoff = cumulative_probs > top_p
        cutoff[..., :min_tokens_to_keep] = False  # keep at least k tokens
        sorted_probs[cutoff] = 0.0
        sorted_probs /= sorted_probs.sum()

        # Sample next token
        next_token = sorted_indices[0, torch.multinomial(sorted_probs, 1).item()].item()
        generated_tokens.add(next_token)

        decoder_input = torch.cat(
            [decoder_input, torch.tensor([[next_token]], device=device)], dim=1
        )

        if next_token == eos_idx:
            break

    return decoder_input.squeeze(0)


def top_p_decode_3(
    model, source, source_mask, tokenizer_tgt, max_len, device,
    top_p=0.8, temperature=0.7, repetition_penalty=1.1, repetition_window=10
):
    """
    Generate DNA sequence (k-mer tokens) conditioned on protein input.
    
    Args:
        model: Transformer model with encode/decode/project methods.
        source: protein input tensor for encoder.
        source_mask: mask for encoder input.
        tokenizer_tgt: tokenizer for DNA k-mer tokens.
        max_len: maximum decoding length.
        device: torch device.
        top_p: nucleus sampling threshold.
        temperature: controls randomness; 1.0 = default, <1 sharp, >1 soft.
        repetition_penalty: penalize tokens repeated in the sliding window.
        repetition_window: number of recent tokens to consider for repetition penalty.
    """
    sos_idx = tokenizer_tgt.token_to_id('[SOS]')
    eos_idx = tokenizer_tgt.token_to_id('[EOS]')
    assert sos_idx is not None and eos_idx is not None

    encoder_output = model.encode(source, source_mask)
    decoder_input = torch.full((1, 1), sos_idx, dtype=torch.long, device=device)

    generated_tokens = []

    for _ in range(max_len):
        decoder_mask = causal_mask(decoder_input.size(1)).type_as(source_mask).to(device)
        out = model.decode(encoder_output, source_mask, decoder_input, decoder_mask)
        logits = model.project(out[:, -1])  # shape: [1, vocab_size]

        # Apply repetition penalty (sliding window)
        if repetition_penalty != 1.0 and generated_tokens:
            window = generated_tokens[-repetition_window:]
            for tok in set(window):
                if logits[0, tok] < 0:
                    logits[0, tok] *= repetition_penalty
                else:
                    logits[0, tok] /= repetition_penalty

        # Apply temperature
        probs = torch.softmax(logits / temperature, dim=-1)

        # Top-p (nucleus) filtering
        sorted_probs, sorted_indices = torch.sort(probs, descending=True)
        cumulative_probs = torch.cumsum(sorted_probs, dim=-1)
        sorted_probs[cumulative_probs > top_p] = 0.0

        # Handle edge case
        if sorted_probs.sum() == 0:
            sorted_probs = torch.ones_like(sorted_probs) / sorted_probs.numel()
        sorted_probs /= sorted_probs.sum()

        # Map back to original indices
        probs_filtered = torch.zeros_like(probs)
        probs_filtered[0, sorted_indices[0]] = sorted_probs[0]

        # Sample next token
        next_token = torch.multinomial(probs_filtered, 1).item()
        generated_tokens.append(next_token)

        # Append to decoder input
        decoder_input = torch.cat(
            [decoder_input, torch.tensor([[next_token]], device=device)], dim=1
        )

        if next_token == eos_idx:
            break

    return torch.tensor(generated_tokens, device=device)


def top_p_decode_4(
    model, source, source_mask, tokenizer_tgt, max_len, device,
    top_p=0.4, temperature=0.3, repetition_penalty=1.1, repetition_window=10
):
    """
    Generate DNA sequence (k-mer tokens) conditioned on protein input.
    
    Args:
        model: Transformer model with encode/decode/project methods.
        source: protein input tensor for encoder.
        source_mask: mask for encoder input.
        tokenizer_tgt: tokenizer for DNA k-mer tokens.
        max_len: maximum decoding length.
        device: torch device.
        top_p: nucleus sampling threshold.
        temperature: controls randomness; 1.0 = default, <1 sharp, >1 soft.
        repetition_penalty: penalize tokens repeated in the sliding window.
        repetition_window: number of recent tokens to consider for repetition penalty.
    """
    sos_idx = tokenizer_tgt.token_to_id('[SOS]')
    eos_idx = tokenizer_tgt.token_to_id('[EOS]')
    assert sos_idx is not None and eos_idx is not None

    encoder_output = model.encode(source, source_mask)
    decoder_input = torch.full((1, 1), sos_idx, dtype=torch.long, device=device)

    generated_tokens = []

    for _ in range(max_len):
        decoder_mask = causal_mask(decoder_input.size(1)).type_as(source_mask).to(device)
        out = model.decode(encoder_output, source_mask, decoder_input, decoder_mask)
        logits = model.project(out[:, -1])  # shape: [1, vocab_size]

        # Apply repetition penalty (sliding window)
        if repetition_penalty != 1.0 and generated_tokens:
            window = generated_tokens[-repetition_window:]
            for tok in set(window):
                if logits[0, tok] < 0:
                    logits[0, tok] *= repetition_penalty
                else:
                    logits[0, tok] /= repetition_penalty

        # Apply temperature
        probs = torch.softmax(logits / temperature, dim=-1)

        # Top-p (nucleus) filtering
        sorted_probs, sorted_indices = torch.sort(probs, descending=True)
        cumulative_probs = torch.cumsum(sorted_probs, dim=-1)
        sorted_probs[cumulative_probs > top_p] = 0.0

        # Handle edge case
        if sorted_probs.sum() == 0:
            sorted_probs = torch.ones_like(sorted_probs) / sorted_probs.numel()
        sorted_probs /= sorted_probs.sum()

        # Map back to original indices
        probs_filtered = torch.zeros_like(probs)
        probs_filtered[0, sorted_indices[0]] = sorted_probs[0]

        # Sample next token
        next_token = torch.multinomial(probs_filtered, 1).item()
        generated_tokens.append(next_token)

        # Append to decoder input
        decoder_input = torch.cat(
            [decoder_input, torch.tensor([[next_token]], device=device)], dim=1
        )

        if next_token == eos_idx:
            break

    return torch.tensor(generated_tokens, device=device)
